# Generated by Django 4.1 on 2022-08-19 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_notifications_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
